name: 'PHPCS'
on: [pull_request]
jobs:
  conditional:
    if: "!contains(github.event.pull_request.body, '[skip-phpcs]')"
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.php_check.outputs.php_files_changed }}
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repo
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          token: ${{ secrets.GH_BOT_TOKEN }}
          submodules: recursive
      # ------------------------------------------------------------------------------
      # Check if any PHP files have changed
      # ------------------------------------------------------------------------------
      - name: Check for PHP file changes
        id: php_check
        uses: the-events-calendar/actions/.github/actions/check-php-changes@main
  phpcs:
    needs: conditional
    if: needs.conditional.outputs.run_tests
    uses: stellarwp/github-actions/.github/workflows/phpcs.yml@main
    with:
      ref: ${{ github.event.inputs.ref }}
      change_permissions: false
    secrets:
      access-token: ${{ secrets.GH_BOT_TOKEN }}
