name: 'EVA Codeception + Woo Tests'
on: [ pull_request ]
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      run_tests: ${{ steps.php_check.outputs.php_files_changed }}
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repo
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          token: ${{ secrets.GH_BOT_TOKEN }}
          submodules: recursive
      # ------------------------------------------------------------------------------
      # Check if any PHP files have changed
      # ------------------------------------------------------------------------------
      - name: Check for PHP file changes
        id: php_check
        uses: ./.github/actions/check-php-changes
      # ------------------------------------------------------------------------------
  test:
    needs: check
    if: needs.check.outputs.run_tests
    strategy:
      fail-fast: false
      matrix:
        suite: [ eva_integration, restv1_et ]
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repo
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_BOT_TOKEN }}
          submodules: recursive
      # ------------------------------------------------------------------------------
      # Checkout slic
      # ------------------------------------------------------------------------------
      - name: Checkout slic
        uses: actions/checkout@v4
        with:
          repository: stellarwp/slic
          ref: main
          path: slic
          fetch-depth: 1
      # ------------------------------------------------------------------------------
      # Prepare our composer cache directory
      # ------------------------------------------------------------------------------
      - name: Get Composer Cache Directory
        id: get-composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v4
        id: composer-cache
        with:
          path: ${{ steps.get-composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      # ------------------------------------------------------------------------------
      # Initialize slic
      # ------------------------------------------------------------------------------
      - name: Move slic directory up
        run: |
          mv slic ./../slic
      - name: Set up slic env vars
        run: |
          echo "SLIC_COMPOSER_VERSION=2" >> $GITHUB_ENV
          echo "SLIC_BIN=${GITHUB_WORKSPACE}/../slic/slic" >> $GITHUB_ENV
          echo "SLIC_WP_DIR=${GITHUB_WORKSPACE}/../slic/_wordpress" >> $GITHUB_ENV
      - name: Set run context for slic
        run: echo "SLIC=1" >> $GITHUB_ENV && echo "CI=1" >> $GITHUB_ENV
      - name: Start ssh-agent
        run: |
          mkdir -p "${HOME}/.ssh";
          ssh-agent -a /tmp/ssh_agent.sock;
      - name: Export SSH_AUTH_SOCK env var
        run: echo "SSH_AUTH_SOCK=/tmp/ssh_agent.sock" >> $GITHUB_ENV
      - name: Set up slic for CI
        run: |
          cd ${GITHUB_WORKSPACE}/..
          ${SLIC_BIN} here
          ${SLIC_BIN} interactive off
          ${SLIC_BIN} build-prompt off
          ${SLIC_BIN} build-subdir off
          ${SLIC_BIN} xdebug off
          ${SLIC_BIN} composer-cache set /home/runner/.cache/composer
          ${SLIC_BIN} debug on
          ${SLIC_BIN} info
          ${SLIC_BIN} config
      # ------------------------------------------------------------------------------
      # Clone dependencies using smart checkout
      # ------------------------------------------------------------------------------
      - name: Clone TEC
        uses: ./.github/actions/smart-checkout
        with:
          other_repo: the-events-calendar/the-events-calendar
          path: the-events-calendar
          token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Init TEC
        run: |
          mv ${GITHUB_WORKSPACE}/the-events-calendar ${GITHUB_WORKSPACE}/../the-events-calendar
          docker network prune -f
          ${SLIC_BIN} use the-events-calendar
          ${SLIC_BIN} composer install --no-dev
      - name: Clone ET
        uses: ./.github/actions/smart-checkout
        with:
          other_repo: the-events-calendar/event-tickets
          path: event-tickets
          token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Init ET
        run: |
          mv ${GITHUB_WORKSPACE}/event-tickets ${GITHUB_WORKSPACE}/../event-tickets
          docker network prune -f
          ${SLIC_BIN} use event-tickets
          ${SLIC_BIN} composer install --no-dev
      - name: Set up Common
        run: |
          docker network prune -f
          ${SLIC_BIN} use event-tickets/common
          ${SLIC_BIN} composer install --no-dev
      - name: Clone ET+
        uses: ./.github/actions/smart-checkout
        with:
          other_repo: the-events-calendar/event-tickets-plus
          path: event-tickets-plus
          token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Init ET+
        run: |
          mv ${GITHUB_WORKSPACE}/event-tickets-plus ${GITHUB_WORKSPACE}/../event-tickets-plus
          docker network prune -f
          ${SLIC_BIN} use event-tickets-plus
          ${SLIC_BIN} composer install --no-dev
      - name: Clone Pro
        uses: ./.github/actions/smart-checkout
        with:
          other_repo: the-events-calendar/events-pro
          path: events-pro
          token: ${{ secrets.GH_BOT_TOKEN }}
      - name: Init Pro
        run: |
          mv ${GITHUB_WORKSPACE}/events-pro ${GITHUB_WORKSPACE}/../events-pro
          docker network prune -f
          ${SLIC_BIN} use events-pro
          ${SLIC_BIN} composer install --no-dev
      # ------------------------------------------------------------------------------
      # Set up Common
      # ------------------------------------------------------------------------------
      - name: Move Common inside TEC
        run: |
          rm -rf ${GITHUB_WORKSPACE}/../the-events-calendar/common
          cp -r ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/../the-events-calendar/common
      # ------------------------------------------------------------------------------
      # Set up Common and run tests
      # ------------------------------------------------------------------------------
      - name: Set up Common
        run: |
          ${SLIC_BIN} use the-events-calendar/common
          ${SLIC_BIN} composer install
      - name: Init the WordPress container and Set up a theme
        run: |
          ${SLIC_BIN} up wordpress
          ${SLIC_BIN} wp core version
          ${SLIC_BIN} wp core update --force --version=6.7
          ${SLIC_BIN} wp core version
          ${SLIC_BIN} wp theme install twentytwenty --activate
      # --------------------------------------------------------------------------
      # Install and activate WooCommerce
      # ------------------------------------------------------------------------------
      - name: Install WooCommerce
        run: ${SLIC_BIN} site-cli plugin install woocommerce --version='9.5.1'
      # ------------------------------------------------------------------------------
      # Run suite tests
      # ------------------------------------------------------------------------------
      - name: Run suite tests
        run: ${SLIC_BIN} run ${{ matrix.suite }}
      # ------------------------------------------------------------------------------
      # Copy test outputs into workspace (On failure)
      # ------------------------------------------------------------------------------
      - name: Copy test outputs into workspace
        if: ${{ failure() }}
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/tests/_output/"
          cp -r "${GITHUB_WORKSPACE}/../the-events-calendar/common/tests/_output/." "${GITHUB_WORKSPACE}/tests/_output/" || echo "No artifacts found to copy."

      # ------------------------------------------------------------------------------
      # Verify artifacts exist
      # ------------------------------------------------------------------------------
      - name: Verify artifacts exist
        if: ${{ failure() }}
        run: |
          echo "Listing contents of '${GITHUB_WORKSPACE}/tests/_output/':"
          ls -la "${GITHUB_WORKSPACE}/tests/_output/" || echo "No artifacts found."

      # ------------------------------------------------------------------------------
      # Upload artifacts (On failure)
      # ------------------------------------------------------------------------------
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: output ${{ matrix.suite }}
          path: tests/_output/
          retention-days: 7
